spring:
  datasource:
    url: jdbc:mysql://b0743eb9d8628d:337b63a4@eu-cdbr-west-03.cleardb.net/heroku_76317c0897bb76d
    username: b0743eb9d8628d
    password: 337b63a4
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
